name: Github CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Install Codon
        run: |
          mkdir -p ${HOME}/.codon
          curl -L https://github.com/exaloop/codon/releases/download/v0.19.3/codon-linux-x86_64.tar.gz \
            | tar zxvf - --strip-components=1 -C ${HOME}/.codon
          curl -L https://github.com/exaloop/seq/releases/download/v0.11.5/seq-linux-x86_64.tar.gz \
            | tar zxvf - -C ${HOME}/.codon/lib/codon/plugins
          export PATH=${PATH}:${HOME}/.codon/bin
      
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Set up Codon Python bridge
        run: |
          pip install find_libpython
          export CODON_PYTHON=$(find_libpython)
          echo "Found Python at: ${CODON_PYTHON}"

      - name: Install bioinformatics tools via conda
        run: |
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          bash Miniforge3-Linux-x86_64.sh -b -p $HOME/miniforge3
          source $HOME/miniforge3/etc/profile.d/conda.sh
          conda activate base
          
          # install everything in one go
          conda install -c bioconda -y samtools bcftools tabix minimap2 hapcut2 htslib
          
          # verify
          echo "=== Checking installed tools ==="
          for tool in bcftools samtools tabix minimap2 HAPCUT2 extractHAIRS; do
            which $tool || echo "âš  $tool not found"
          done

      
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      # - name: make evaluate executable 
      #   run: chmod +x week1/evaluate.sh
        
      # - name: Week 1
      #   run: bash week1/evaluate.sh

      # - run: python -m pip install "numpy>=2.1"
      # - name: Week 3
      #   run: bash week3/evaluate.sh
      
      # - name: make evaluate executable week4
      #   run: chmod +x week4/evaluate.sh
        
      # - name: Week 4
      #   run: bash week4/evaluate.sh

      - name: Week5
        run: jupyter execute week5/week5-test.ipynb

